TYPE=VIEW
query=select `english`.`announces`.`id` AS `id`,`english`.`announces`.`kbn` AS `kbn`,`english`.`announces`.`device_display` AS `device_display`,`english`.`announces`.`disp_date` AS `disp_date`,`cc`.`iso_639_1` AS `language`,`english`.`global_announces`.`gl_title` AS `title`,`english`.`global_announces`.`gl_content` AS `content`,`english`.`country_codes`.`iso_639_1` AS `supported_language`,`english`.`announce_currency`.`currency_code` AS `supported_currency`,`english`.`announce_membership_types`.`membership_type` AS `membership_type` from ((((((`english`.`announces` left join `english`.`global_announces` on((`english`.`global_announces`.`announce_id` = `english`.`announces`.`id`))) join `english`.`country_codes` `cc` on((`english`.`global_announces`.`language_id` = `cc`.`id`))) join `english`.`announce_language` on((`english`.`global_announces`.`announce_id` = `english`.`announce_language`.`announce_id`))) join `english`.`country_codes` on((`english`.`announce_language`.`language_id` = `english`.`country_codes`.`id`))) join `english`.`announce_currency` on((`english`.`global_announces`.`announce_id` = `english`.`announce_currency`.`announce_id`))) left join `english`.`announce_membership_types` on((`english`.`announce_membership_types`.`announce_id` = `english`.`announces`.`id`))) where ((`english`.`announces`.`status` = 1) and (`english`.`announces`.`start_time` <= now()) and (`english`.`announces`.`end_time` >= now()))
md5=1efa20d63f33ab6308794110a78fede8
updatable=0
algorithm=0
definer_user=ncwww
definer_host=%
suid=1
with_check_option=0
timestamp=2021-11-18 02:57:49
create-version=1
source=select `announces`.`id` AS `id`,`announces`.`kbn` AS `kbn`,`announces`.`device_display` AS `device_display`,`announces`.`disp_date` AS `disp_date`,`cc`.`iso_639_1` AS `language`,`global_announces`.`gl_title` AS `title`,`global_announces`.`gl_content` AS `content`,`country_codes`.`iso_639_1` AS `supported_language`,`announce_currency`.`currency_code` AS `supported_currency`,`announce_membership_types`.`membership_type` AS `membership_type` from ((((((`announces` left join `global_announces` on((`global_announces`.`announce_id` = `announces`.`id`))) join `country_codes` `cc` on((`global_announces`.`language_id` = `cc`.`id`))) join `announce_language` on((`global_announces`.`announce_id` = `announce_language`.`announce_id`))) join `country_codes` on((`announce_language`.`language_id` = `country_codes`.`id`))) join `announce_currency` on((`global_announces`.`announce_id` = `announce_currency`.`announce_id`))) left join `announce_membership_types` on((`announce_membership_types`.`announce_id` = `announces`.`id`))) where ((`announces`.`status` = 1) and (`announces`.`start_time` <= now()) and (`announces`.`end_time` >= now()))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `english`.`announces`.`id` AS `id`,`english`.`announces`.`kbn` AS `kbn`,`english`.`announces`.`device_display` AS `device_display`,`english`.`announces`.`disp_date` AS `disp_date`,`cc`.`iso_639_1` AS `language`,`english`.`global_announces`.`gl_title` AS `title`,`english`.`global_announces`.`gl_content` AS `content`,`english`.`country_codes`.`iso_639_1` AS `supported_language`,`english`.`announce_currency`.`currency_code` AS `supported_currency`,`english`.`announce_membership_types`.`membership_type` AS `membership_type` from ((((((`english`.`announces` left join `english`.`global_announces` on((`english`.`global_announces`.`announce_id` = `english`.`announces`.`id`))) join `english`.`country_codes` `cc` on((`english`.`global_announces`.`language_id` = `cc`.`id`))) join `english`.`announce_language` on((`english`.`global_announces`.`announce_id` = `english`.`announce_language`.`announce_id`))) join `english`.`country_codes` on((`english`.`announce_language`.`language_id` = `english`.`country_codes`.`id`))) join `english`.`announce_currency` on((`english`.`global_announces`.`announce_id` = `english`.`announce_currency`.`announce_id`))) left join `english`.`announce_membership_types` on((`english`.`announce_membership_types`.`announce_id` = `english`.`announces`.`id`))) where ((`english`.`announces`.`status` = 1) and (`english`.`announces`.`start_time` <= now()) and (`english`.`announces`.`end_time` >= now()))
