TYPE=VIEW
query=select `english`.`learning_contents`.`id` AS `id`,`english`.`country_codes`.`iso_639_1` AS `language`,`english`.`global_learning_contents`.`gl_title` AS `gl_title`,`english`.`global_learning_contents`.`gl_subtitle` AS `gl_subtitle`,`english`.`global_learning_contents`.`gl_description` AS `gl_description`,`english`.`global_learning_contents`.`gl_copyright_information` AS `gl_copyright_information`,`english`.`global_learning_contents`.`gl_photo_copyright` AS `gl_photo_copyright`,`english`.`global_learning_contents`.`gl_illustration_copyright` AS `gl_illustration_copyright`,`english`.`global_learning_contents`.`gl_image_copyright` AS `gl_image_copyright`,`english`.`global_learning_contents`.`gl_text` AS `gl_text`,`english`.`global_learning_contents`.`gl_text_copyright` AS `gl_text_copyright`,`english`.`global_learning_contents`.`gl_note` AS `gl_note`,`english`.`global_learning_contents`.`gl_audio_copyright` AS `gl_audio_copyright`,`english`.`global_learning_contents`.`gl_text_translation` AS `gl_text_translation`,`english`.`global_learning_contents`.`gl_keyword` AS `gl_keyword`,`english`.`global_learning_contents`.`gl_source` AS `gl_source`,`english`.`global_learning_contents`.`overwrite_protection` AS `overwrite_protection` from ((`english`.`learning_contents` left join `english`.`global_learning_contents` on((`english`.`learning_contents`.`id` = `english`.`global_learning_contents`.`content_id`))) join `english`.`country_codes` on((`english`.`global_learning_contents`.`language_id` = `english`.`country_codes`.`id`)))
md5=c9902d91bd3ffa97c0b938978e71180b
updatable=0
algorithm=0
definer_user=ncwww
definer_host=%
suid=1
with_check_option=0
timestamp=2021-11-18 02:58:13
create-version=1
source=select `learning_contents`.`id` AS `id`,`country_codes`.`iso_639_1` AS `language`,`global_learning_contents`.`gl_title` AS `gl_title`,`global_learning_contents`.`gl_subtitle` AS `gl_subtitle`,`global_learning_contents`.`gl_description` AS `gl_description`,`global_learning_contents`.`gl_copyright_information` AS `gl_copyright_information`,`global_learning_contents`.`gl_photo_copyright` AS `gl_photo_copyright`,`global_learning_contents`.`gl_illustration_copyright` AS `gl_illustration_copyright`,`global_learning_contents`.`gl_image_copyright` AS `gl_image_copyright`,`global_learning_contents`.`gl_text` AS `gl_text`,`global_learning_contents`.`gl_text_copyright` AS `gl_text_copyright`,`global_learning_contents`.`gl_note` AS `gl_note`,`global_learning_contents`.`gl_audio_copyright` AS `gl_audio_copyright`,`global_learning_contents`.`gl_text_translation` AS `gl_text_translation`,`global_learning_contents`.`gl_keyword` AS `gl_keyword`,`global_learning_contents`.`gl_source` AS `gl_source`,`global_learning_contents`.`overwrite_protection` AS `overwrite_protection` from ((`learning_contents` left join `global_learning_contents` on((`learning_contents`.`id` = `global_learning_contents`.`content_id`))) join `country_codes` on((`global_learning_contents`.`language_id` = `country_codes`.`id`)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `english`.`learning_contents`.`id` AS `id`,`english`.`country_codes`.`iso_639_1` AS `language`,`english`.`global_learning_contents`.`gl_title` AS `gl_title`,`english`.`global_learning_contents`.`gl_subtitle` AS `gl_subtitle`,`english`.`global_learning_contents`.`gl_description` AS `gl_description`,`english`.`global_learning_contents`.`gl_copyright_information` AS `gl_copyright_information`,`english`.`global_learning_contents`.`gl_photo_copyright` AS `gl_photo_copyright`,`english`.`global_learning_contents`.`gl_illustration_copyright` AS `gl_illustration_copyright`,`english`.`global_learning_contents`.`gl_image_copyright` AS `gl_image_copyright`,`english`.`global_learning_contents`.`gl_text` AS `gl_text`,`english`.`global_learning_contents`.`gl_text_copyright` AS `gl_text_copyright`,`english`.`global_learning_contents`.`gl_note` AS `gl_note`,`english`.`global_learning_contents`.`gl_audio_copyright` AS `gl_audio_copyright`,`english`.`global_learning_contents`.`gl_text_translation` AS `gl_text_translation`,`english`.`global_learning_contents`.`gl_keyword` AS `gl_keyword`,`english`.`global_learning_contents`.`gl_source` AS `gl_source`,`english`.`global_learning_contents`.`overwrite_protection` AS `overwrite_protection` from ((`english`.`learning_contents` left join `english`.`global_learning_contents` on((`english`.`learning_contents`.`id` = `english`.`global_learning_contents`.`content_id`))) join `english`.`country_codes` on((`english`.`global_learning_contents`.`language_id` = `english`.`country_codes`.`id`)))
