TYPE=VIEW
query=select `english`.`multilingual_faq`.`id` AS `id`,`english`.`multilingual_faq`.`destination` AS `destination`,`english`.`country_codes`.`iso_639_1` AS `language`,`english`.`global_multilingual_faq`.`gl_title` AS `gl_title`,`english`.`global_multilingual_faq`.`gl_content` AS `gl_content`,`english`.`multilingual_faq_currency`.`currency_code` AS `supported_currency`,`cc`.`iso_639_1` AS `supported_language` from (((((`english`.`multilingual_faq` left join `english`.`global_multilingual_faq` on((`english`.`multilingual_faq`.`id` = `english`.`global_multilingual_faq`.`multilingual_faq_id`))) join `english`.`country_codes` on((`english`.`global_multilingual_faq`.`language_id` = `english`.`country_codes`.`id`))) left join `english`.`multilingual_faq_currency` on((`english`.`multilingual_faq_currency`.`multilingual_faq_id` = `english`.`multilingual_faq`.`id`))) left join `english`.`multilingual_faq_language` on((`english`.`multilingual_faq_language`.`multilingual_faq_id` = `english`.`multilingual_faq`.`id`))) join `english`.`country_codes` `cc` on((`english`.`multilingual_faq_language`.`language_id` = `cc`.`id`))) where (`english`.`multilingual_faq`.`status` = 1) order by `english`.`multilingual_faq`.`sort`
md5=69573aef7cdb004557f39f50d73cdc4d
updatable=0
algorithm=0
definer_user=ncwww
definer_host=%
suid=1
with_check_option=0
timestamp=2021-11-18 02:58:29
create-version=1
source=select `multilingual_faq`.`id` AS `id`,`multilingual_faq`.`destination` AS `destination`,`country_codes`.`iso_639_1` AS `language`,`global_multilingual_faq`.`gl_title` AS `gl_title`,`global_multilingual_faq`.`gl_content` AS `gl_content`,`multilingual_faq_currency`.`currency_code` AS `supported_currency`,`cc`.`iso_639_1` AS `supported_language` from (((((`multilingual_faq` left join `global_multilingual_faq` on((`multilingual_faq`.`id` = `global_multilingual_faq`.`multilingual_faq_id`))) join `country_codes` on((`global_multilingual_faq`.`language_id` = `country_codes`.`id`))) left join `multilingual_faq_currency` on((`multilingual_faq_currency`.`multilingual_faq_id` = `multilingual_faq`.`id`))) left join `multilingual_faq_language` on((`multilingual_faq_language`.`multilingual_faq_id` = `multilingual_faq`.`id`))) join `country_codes` `cc` on((`multilingual_faq_language`.`language_id` = `cc`.`id`))) where (`multilingual_faq`.`status` = 1) order by `multilingual_faq`.`sort`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `english`.`multilingual_faq`.`id` AS `id`,`english`.`multilingual_faq`.`destination` AS `destination`,`english`.`country_codes`.`iso_639_1` AS `language`,`english`.`global_multilingual_faq`.`gl_title` AS `gl_title`,`english`.`global_multilingual_faq`.`gl_content` AS `gl_content`,`english`.`multilingual_faq_currency`.`currency_code` AS `supported_currency`,`cc`.`iso_639_1` AS `supported_language` from (((((`english`.`multilingual_faq` left join `english`.`global_multilingual_faq` on((`english`.`multilingual_faq`.`id` = `english`.`global_multilingual_faq`.`multilingual_faq_id`))) join `english`.`country_codes` on((`english`.`global_multilingual_faq`.`language_id` = `english`.`country_codes`.`id`))) left join `english`.`multilingual_faq_currency` on((`english`.`multilingual_faq_currency`.`multilingual_faq_id` = `english`.`multilingual_faq`.`id`))) left join `english`.`multilingual_faq_language` on((`english`.`multilingual_faq_language`.`multilingual_faq_id` = `english`.`multilingual_faq`.`id`))) join `english`.`country_codes` `cc` on((`english`.`multilingual_faq_language`.`language_id` = `cc`.`id`))) where (`english`.`multilingual_faq`.`status` = 1) order by `english`.`multilingual_faq`.`sort`
